"""Add file_hash field to documents table

Revision ID: 0971a4e68cb3
Revises: 8b99ca9ade15
Create Date: 2025-09-13 13:51:04.577573

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0971a4e68cb3"
down_revision: Union[str, None] = "8b99ca9ade15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_hash", sa.String(length=64), nullable=False)
    )
    op.create_index(
        op.f("ix_documents_file_hash"), "documents", ["file_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_file_hash"), table_name="documents")
    op.drop_column("documents", "file_hash")
    # ### end Alembic commands ###
