"""add_filename_field


Revision ID: e3b02a923aea
Revises: 0971a4e68cb3
Create Date: 2025-09-14 12:49:05.374619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3b02a923aea"
down_revision: Union[str, None] = "0971a4e68cb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("file_name", sa.String(length=500), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "file_name")
    # ### end Alembic commands ###
